### ISSUE TITLE
Site out of sync with master

### ISSUE THREAD

**Issue by BaconSoap** [NGPVAN/developers.ngpvan.com#79]
Master hasn't been deployed in a while. Among other things, this means that the instructions for the `Content-Type` header aren't visible - something that bites almost every single person that tries to use our API, including internal developers!

@itsdrewmiller @lebowitz can we get the deployed version up to date?

**Comment by itsdrewmiller** [comment]
I deployed this yesterday...

Mobile: (515) 451-4509
Fax: Click here

**Comment by BaconSoap** [comment]
My pull request was merged to master and then was force pushed into oblivion :(, which made me think that we hadn't deployed. Opened it again...
